// Lily# - Music notation compiler
// AUTO-GENERATED by audit/scripts/Extract-EmmentalerMetrics.py — DO NOT EDIT MANUALLY.
// Re-run the script after the bundled Emmentaler font is updated.
// Source font: editors/vscode/server/Fonts/emmentaler-20.otf
// 1 staff space = unitsPerEm / 4 = 250 font units
//
// Hand-tuned constants (engraving thicknesses, spacing heuristics, LP grob
// defaults) live in GlyphMetrics.cs — this file holds only values that can
// be derived directly from the font binary.

namespace LilySharp.Core.Svg.Layout;

public static partial class GlyphMetrics
{
    // ========== BBox glyphs (extracted from font outlines) ==========
    // BBox = true visual extent (use for collision / skyline). For horizontal
    // positioning of the next glyph use the corresponding ...Advance constant —
    // notehead glyphs have decorative serifs that overhang the advance width.

    /// <summary>Whole notehead — BBox.</summary>
    /// <remarks>LILYPOND-REF: mf/feta-noteheads.mf — noteheads.s0 (U+E0E8 = noteheads.s0)</remarks>
    public static readonly BBox NoteheadWhole = new(0.0000, -0.5440, 1.9640, 0.5440);
    /// <summary>Whole notehead — advance width (next-glyph horizontal feed).</summary>
    public const double NoteheadWholeAdvance = 1.9600;

    /// <summary>Half (hollow) notehead — BBox.</summary>
    /// <remarks>LILYPOND-REF: mf/feta-noteheads.mf — noteheads.s1 (U+E0E9 = noteheads.s1)</remarks>
    public static readonly BBox NoteheadHalf = new(0.0000, -0.5440, 1.3760, 0.5440);
    /// <summary>Half (hollow) notehead — advance width (next-glyph horizontal feed).</summary>
    public const double NoteheadHalfAdvance = 1.3760;

    /// <summary>Black (filled) notehead — BBox.</summary>
    /// <remarks>LILYPOND-REF: mf/feta-noteheads.mf — noteheads.s2 (U+E0EA = noteheads.s2)</remarks>
    public static readonly BBox NoteheadBlack = new(0.0000, -0.5440, 1.3040, 0.5440);
    /// <summary>Black (filled) notehead — advance width (next-glyph horizontal feed).</summary>
    public const double NoteheadBlackAdvance = 1.3040;

    /// <summary>Sharp accidental — BBox.</summary>
    /// <remarks>LILYPOND-REF: mf/feta-accidentals.mf — accidentals.sharp (U+E013 = accidentals.sharp)</remarks>
    public static readonly BBox AccidentalSharp = new(0.0000, -1.5000, 1.1000, 1.5000);
    /// <summary>Sharp accidental — advance width (next-glyph horizontal feed).</summary>
    public const double AccidentalSharpAdvance = 1.1000;

    /// <summary>Flat accidental — BBox.</summary>
    /// <remarks>LILYPOND-REF: mf/feta-flats.mf — accidentals.flat (U+E021 = accidentals.flat)</remarks>
    public static readonly BBox AccidentalFlat = new(-0.1080, -0.6520, 0.8000, 1.8600);
    /// <summary>Flat accidental — advance width (next-glyph horizontal feed).</summary>
    public const double AccidentalFlatAdvance = 0.8000;

    /// <summary>Natural accidental — BBox.</summary>
    /// <remarks>LILYPOND-REF: mf/feta-accidentals.mf — accidentals.natural (U+E01D = accidentals.natural)</remarks>
    public static readonly BBox AccidentalNatural = new(-0.0280, -1.5280, 0.6960, 1.5280);
    /// <summary>Natural accidental — advance width (next-glyph horizontal feed).</summary>
    public const double AccidentalNaturalAdvance = 0.6640;

    /// <summary>Double sharp accidental — BBox.</summary>
    /// <remarks>LILYPOND-REF: mf/feta-accidentals.mf — accidentals.doublesharp (U+E01C = accidentals.doublesharp)</remarks>
    public static readonly BBox AccidentalDoubleSharp = new(-0.0405, -0.5405, 1.0405, 0.5405);
    /// <summary>Double sharp accidental — advance width (next-glyph horizontal feed).</summary>
    public const double AccidentalDoubleSharpAdvance = 1.0000;

    /// <summary>Double flat accidental — BBox.</summary>
    /// <remarks>LILYPOND-REF: mf/feta-flats.mf — accidentals.flatflat (U+E02A = accidentals.flatflat)</remarks>
    public static readonly BBox AccidentalDoubleFlat = new(-0.1080, -0.6520, 1.4480, 1.8600);
    /// <summary>Double flat accidental — advance width (next-glyph horizontal feed).</summary>
    public const double AccidentalDoubleFlatAdvance = 1.4480;

    /// <summary>Left accidental parenthesis (ink left of origin, advance 0) — BBox.</summary>
    /// <remarks>LILYPOND-REF: mf/feta-parenthesis.mf — accidentals.leftparen (U+E02F = accidentals.leftparen)</remarks>
    public static readonly BBox AccidentalLeftParen = new(-0.6000, -1.0520, -0.1480, 1.0520);
    /// <summary>Left accidental parenthesis (ink left of origin, advance 0) — advance width (next-glyph horizontal feed).</summary>
    public const double AccidentalLeftParenAdvance = 0.0000;

    /// <summary>Right accidental parenthesis — BBox.</summary>
    /// <remarks>LILYPOND-REF: mf/feta-parenthesis.mf — accidentals.rightparen (U+E02E = accidentals.rightparen)</remarks>
    public static readonly BBox AccidentalRightParen = new(0.1480, -1.0520, 0.6000, 1.0520);
    /// <summary>Right accidental parenthesis — advance width (next-glyph horizontal feed).</summary>
    public const double AccidentalRightParenAdvance = 0.6000;

    /// <summary>8th note flag (upward stem) — BBox.</summary>
    /// <remarks>LILYPOND-REF: mf/feta-flags.mf — flags.u3 (U+E0D2 = flags.u3)</remarks>
    public static readonly BBox Flag8thUp = new(-0.0640, -3.0080, 0.8280, 0.0000);
    /// <summary>8th note flag (upward stem) — advance width (next-glyph horizontal feed).</summary>
    public const double Flag8thUpAdvance = 0.8280;

    /// <summary>8th note flag (downward stem) — BBox.</summary>
    /// <remarks>LILYPOND-REF: mf/feta-flags.mf — flags.d3 (U+E0DA = flags.d3)</remarks>
    public static readonly BBox Flag8thDown = new(-0.0640, 0.0000, 1.0680, 2.7960);
    /// <summary>8th note flag (downward stem) — advance width (next-glyph horizontal feed).</summary>
    public const double Flag8thDownAdvance = 1.0640;

    /// <summary>16th note flag (upward stem) — BBox.</summary>
    /// <remarks>LILYPOND-REF: mf/feta-flags.mf — flags.u4 (U+E0D3 = flags.u4)</remarks>
    public static readonly BBox Flag16thUp = new(-0.0640, -3.5080, 0.8280, 0.0000);
    /// <summary>16th note flag (upward stem) — advance width (next-glyph horizontal feed).</summary>
    public const double Flag16thUpAdvance = 0.8280;

    /// <summary>16th note flag (downward stem) — BBox.</summary>
    /// <remarks>LILYPOND-REF: mf/feta-flags.mf — flags.d4 (U+E0DB = flags.d4)</remarks>
    public static readonly BBox Flag16thDown = new(-0.0640, 0.0000, 1.0680, 3.0080);
    /// <summary>16th note flag (downward stem) — advance width (next-glyph horizontal feed).</summary>
    public const double Flag16thDownAdvance = 1.0640;

    /// <summary>Augmentation dot — BBox.</summary>
    /// <remarks>LILYPOND-REF: mf/feta-noteheads.mf — dots.dot (U+E038 = dots.dot)</remarks>
    public static readonly BBox AugmentationDot = new(0.0000, -0.2240, 0.4480, 0.2240);
    /// <summary>Augmentation dot — advance width (next-glyph horizontal feed).</summary>
    public const double AugmentationDotAdvance = 0.4480;

    /// <summary>Trill ornament — BBox.</summary>
    /// <remarks>LILYPOND-REF: mf/feta-scripts.mf — scripts.trill (U+E05C = scripts.trill)</remarks>
    public static readonly BBox OrnTrillGlyph = new(-1.2880, -0.0440, 1.1080, 2.1600);
    /// <summary>Trill ornament — advance width (next-glyph horizontal feed).</summary>
    public const double OrnTrillGlyphAdvance = 0.8480;

    /// <summary>Segno mark — BBox.</summary>
    /// <remarks>LILYPOND-REF: mf/feta-scripts.mf — scripts.segno (U+E062 = scripts.segno)</remarks>
    public static readonly BBox MarkSegno = new(-1.0000, -1.5000, 1.0000, 1.5000);
    /// <summary>Segno mark — advance width (next-glyph horizontal feed).</summary>
    public const double MarkSegnoAdvance = 1.0000;

    /// <summary>Coda mark — BBox.</summary>
    /// <remarks>LILYPOND-REF: mf/feta-scripts.mf — scripts.coda (U+E064 = scripts.coda)</remarks>
    public static readonly BBox MarkCoda = new(-1.0760, -1.4120, 1.0760, 1.4120);
    /// <summary>Coda mark — advance width (next-glyph horizontal feed).</summary>
    public const double MarkCodaAdvance = 1.0160;

    /// <summary>Whole rest — BBox.</summary>
    /// <remarks>LILYPOND-REF: mf/feta-rests.mf — rests.0 (U+E000 = rests.0)</remarks>
    public static readonly BBox RestWhole = new(0.0000, -0.6240, 1.5000, 0.0000);
    /// <summary>Whole rest — advance width (next-glyph horizontal feed).</summary>
    public const double RestWholeAdvance = 1.5000;

    /// <summary>Half rest — BBox.</summary>
    /// <remarks>LILYPOND-REF: mf/feta-rests.mf — rests.1 (U+E001 = rests.1)</remarks>
    public static readonly BBox RestHalf = new(0.0000, 0.0000, 1.5000, 0.6240);
    /// <summary>Half rest — advance width (next-glyph horizontal feed).</summary>
    public const double RestHalfAdvance = 1.5000;

    /// <summary>Quarter rest — BBox.</summary>
    /// <remarks>LILYPOND-REF: mf/feta-rests.mf — rests.2 (U+E008 = rests.2)</remarks>
    public static readonly BBox RestQuarter = new(-0.0920, -1.2831, 0.9720, 1.5840);
    /// <summary>Quarter rest — advance width (next-glyph horizontal feed).</summary>
    public const double RestQuarterAdvance = 0.9480;

    /// <summary>8th rest — BBox.</summary>
    /// <remarks>LILYPOND-REF: mf/feta-rests.mf — rests.3 (U+E00B = rests.3)</remarks>
    public static readonly BBox Rest8th = new(-0.0120, -1.0400, 1.0000, 0.8200);
    /// <summary>8th rest — advance width (next-glyph horizontal feed).</summary>
    public const double Rest8thAdvance = 1.0000;

    /// <summary>16th rest — BBox.</summary>
    /// <remarks>LILYPOND-REF: mf/feta-rests.mf — rests.4 (U+E00C = rests.4)</remarks>
    public static readonly BBox Rest16th = new(-0.1040, -2.0400, 1.2000, 0.8200);
    /// <summary>16th rest — advance width (next-glyph horizontal feed).</summary>
    public const double Rest16thAdvance = 1.1960;

    /// <summary>32nd rest — BBox.</summary>
    /// <remarks>LILYPOND-REF: mf/feta-rests.mf — rests.5 (U+E00D = rests.5)</remarks>
    public static readonly BBox Rest32nd = new(-0.2200, -2.0400, 1.3000, 1.8200);
    /// <summary>32nd rest — advance width (next-glyph horizontal feed).</summary>
    public const double Rest32ndAdvance = 1.3000;

    /// <summary>64th rest — BBox.</summary>
    /// <remarks>LILYPOND-REF: mf/feta-rests.mf — rests.6 (U+E00E = rests.6)</remarks>
    public static readonly BBox Rest64th = new(-0.2680, -3.0400, 1.4000, 1.8200);
    /// <summary>64th rest — advance width (next-glyph horizontal feed).</summary>
    public const double Rest64thAdvance = 1.3960;

    /// <summary>128th rest — BBox.</summary>
    /// <remarks>LILYPOND-REF: mf/feta-rests.mf — rests.7 (U+E00F = rests.7)</remarks>
    public static readonly BBox Rest128th = new(-0.2400, -3.0400, 1.5000, 2.8200);
    /// <summary>128th rest — advance width (next-glyph horizontal feed).</summary>
    public const double Rest128thAdvance = 1.5000;

    /// <summary>Staccato dot articulation — BBox.</summary>
    /// <remarks>LILYPOND-REF: mf/feta-scripts.mf — scripts.staccato (U+E04A = scripts.staccato)</remarks>
    public static readonly BBox ArticStaccato = new(-0.2000, -0.2000, 0.2000, 0.2000);
    /// <summary>Staccato dot articulation — advance width (next-glyph horizontal feed).</summary>
    public const double ArticStaccatoAdvance = 0.1960;

    /// <summary>Accent / sforzato articulation — BBox.</summary>
    /// <remarks>LILYPOND-REF: mf/feta-scripts.mf — scripts.sforzato (U+E048 = scripts.sforzato)</remarks>
    public static readonly BBox ArticAccent = new(-0.7520, -0.4200, 0.7520, 0.4200);
    /// <summary>Accent / sforzato articulation — advance width (next-glyph horizontal feed).</summary>
    public const double ArticAccentAdvance = 0.7480;

    /// <summary>Tenuto articulation — BBox.</summary>
    /// <remarks>LILYPOND-REF: mf/feta-scripts.mf — scripts.tenuto (U+E04D = scripts.tenuto)</remarks>
    public static readonly BBox ArticTenuto = new(-0.6000, -0.0800, 0.6000, 0.0800);
    /// <summary>Tenuto articulation — advance width (next-glyph horizontal feed).</summary>
    public const double ArticTenutoAdvance = 0.6000;

    /// <summary>Marcato above (upward V) — BBox.</summary>
    /// <remarks>LILYPOND-REF: mf/feta-scripts.mf — scripts.umarcato (U+E050 = scripts.umarcato)</remarks>
    public static readonly BBox ArticMarcatoAbove = new(-0.5006, 0.0000, 0.5006, 1.1000);
    /// <summary>Marcato above (upward V) — advance width (next-glyph horizontal feed).</summary>
    public const double ArticMarcatoAboveAdvance = 0.5000;

    /// <summary>Marcato below (downward V) — BBox.</summary>
    /// <remarks>LILYPOND-REF: mf/feta-scripts.mf — scripts.dmarcato (U+E051 = scripts.dmarcato)</remarks>
    public static readonly BBox ArticMarcatoBelow = new(-0.5006, -1.1000, 0.5006, 0.0000);
    /// <summary>Marcato below (downward V) — advance width (next-glyph horizontal feed).</summary>
    public const double ArticMarcatoBelowAdvance = 0.5000;

    // ========== Advance widths (extracted from hmtx table) ==========

    /// <summary>G (treble) clef advance width</summary>
    /// <remarks>LILYPOND-REF: mf/feta-clefs.mf — clefs.G (U+E085 = clefs.G)</remarks>
    public const double GClefAdvance = 2.5640;

    /// <summary>F (bass) clef advance width</summary>
    /// <remarks>LILYPOND-REF: mf/feta-clefs.mf — clefs.F (U+E083 = clefs.F)</remarks>
    public const double FClefAdvance = 2.6800;

    /// <summary>C (alto/tenor) clef advance width</summary>
    /// <remarks>LILYPOND-REF: mf/feta-clefs.mf — clefs.C (U+E07F = clefs.C)</remarks>
    public const double CClefAdvance = 2.7200;

    /// <summary>Time signature '0' digit advance width</summary>
    /// <remarks>LILYPOND-REF: mf/feta-numbers.mf — fattened.zero (U+E0B4 = fattened.zero)</remarks>
    public const double TimeSigDigit0Advance = 1.4640;

    /// <summary>Time signature '1' digit advance width</summary>
    /// <remarks>LILYPOND-REF: mf/feta-numbers.mf — fattened.one (U+E0B5 = fattened.one)</remarks>
    public const double TimeSigDigit1Advance = 1.2920;

    /// <summary>Time signature '2' digit advance width</summary>
    /// <remarks>LILYPOND-REF: mf/feta-numbers.mf — fattened.two (U+E0B6 = fattened.two)</remarks>
    public const double TimeSigDigit2Advance = 1.4640;

    /// <summary>Time signature '3' digit advance width</summary>
    /// <remarks>LILYPOND-REF: mf/feta-numbers.mf — fattened.three (U+E0B7 = fattened.three)</remarks>
    public const double TimeSigDigit3Advance = 1.3320;

    /// <summary>Time signature '4' digit advance width</summary>
    /// <remarks>LILYPOND-REF: mf/feta-numbers.mf — fattened.four (U+E0B8 = fattened.four)</remarks>
    public const double TimeSigDigit4Advance = 1.6000;

    /// <summary>Time signature '5' digit advance width</summary>
    /// <remarks>LILYPOND-REF: mf/feta-numbers.mf — fattened.five (U+E0BA = fattened.five)</remarks>
    public const double TimeSigDigit5Advance = 1.3480;

    /// <summary>Time signature '6' digit advance width</summary>
    /// <remarks>LILYPOND-REF: mf/feta-numbers.mf — fattened.six (U+E0BB = fattened.six)</remarks>
    public const double TimeSigDigit6Advance = 1.3560;

    /// <summary>Time signature '7' digit advance width</summary>
    /// <remarks>LILYPOND-REF: mf/feta-numbers.mf — fattened.seven (U+E0BC = fattened.seven)</remarks>
    public const double TimeSigDigit7Advance = 1.2880;

    /// <summary>Time signature '8' digit advance width</summary>
    /// <remarks>LILYPOND-REF: mf/feta-numbers.mf — fattened.eight (U+E0BE = fattened.eight)</remarks>
    public const double TimeSigDigit8Advance = 1.4640;

    /// <summary>Time signature '9' digit advance width</summary>
    /// <remarks>LILYPOND-REF: mf/feta-numbers.mf — fattened.nine (U+E0BF = fattened.nine)</remarks>
    public const double TimeSigDigit9Advance = 1.3560;

}
