#!/usr/bin/env python3
"""Counts and lists what the engine KNOWS it has not ported, and whether anything watches it.

WHY THIS EXISTS (HANDOFF section 5, 2026-08-11). The ledger says whether the places we
MEASURED agree with LilyPond. It cannot say how many places we deliberately did NOT measure,
and those are recorded honestly but only in prose, one comment at a time, across 32 files.
Nobody knows the total -- so nobody can tell "every measured point is exact and the machine is
the same shape" from "every measured point is exact and the machine has quietly drifted".
This turns that prose into a number and a list.

It is a TRIAGE tool, not a verdict: a site on this list is not a defect. Most of them are
deliberate, argued and correct. The question the list answers is "how many, and where are they
clustered", which is a thing you can only act on once you can see it.

Run:  py -3.13 audit/scripts/Build-ApproximationInventory.py
Writes docs/APPROXIMATIONS.md and prints the totals.
"""
from __future__ import annotations

import re
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "LilySharp.Core"
OUT = ROOT / "docs" / "APPROXIMATIONS.md"

# Three kinds, and they are NOT the same thing -- keeping them apart is most of the value.
#   OWN        the comment claims LilyPond has no counterpart at all
#   APPROX     a port that is knowingly not the shape of LilyPond's
#   UNWATCHED  a divergence the comment says nothing observes
CATEGORIES: list[tuple[str, str, re.Pattern[str]]] = [
    ("APPROX", "LP に対応物はあるが、形が違うと自認しているもの",
     re.compile(r"DERIVATION, NOT A TRANSCRIPTION|NOT PORTED HERE|NOT PORTED:|"
                r"\bnot ported\b|IS NOT PORTED|approximation the|"
                r"the same approximation|silently approximated", re.I)),
    ("UNWATCHED", "観測者がゼロだと自認しているもの",
     re.compile(r"no ledger point|No ledger point|no point (?:measures|observes|watches|"
                r"reaches|is)|nothing watches|no observer|unobserved|"
                r"observer(?:s)? (?:is|are) zero|no book reaches|reaches that texture", re.I)),
    ("OWN", "LilyPond に対応物が無いと宣言しているもの (LILYSHARP-OWN)",
     re.compile(r"LILYSHARP-OWN")),
]

# A mention of the marker is not a declaration of it. The session-158 audit of the OWN
# list found ~1 in 7 hits were HISTORY ("was/were/declared LILYSHARP-OWN until ...") or
# META ("it is NOT LILYSHARP-OWN") — counting those inflates the OWN total and makes the
# next reader hunt labels that no longer exist. The keyword must precede the marker on
# the SAME line (live labels put "not"/"declared" only AFTER it: "LILYSHARP-OWN,
# DECLARED:"), and cross-references were reworded at their sites instead of matched here.
# The gap may not cross a sentence end, but a decimal ("Was an invented 0.3 (…") is not
# one — hence the tempered dot.
OWN_MENTION = re.compile(
    r"\b(?:was|were|used to|declared|not|than as)\b(?:[^.]|\.(?=\d)){0,40}LILYSHARP-OWN"
    r"|LILYSHARP-OWN line\b", re.I)

COMMENT = re.compile(r"^\s*(?:///|//|\*)\s?")


def clean(line: str) -> str:
    s = COMMENT.sub("", line.rstrip())
    s = re.sub(r"<[^>]+>", "", s)          # XML doc tags carry no information here
    s = re.sub(r"\s+", " ", s).strip()
    return s


def main() -> int:
    files = sorted(
        p for p in SRC.rglob("*.cs")
        if "\\bin\\" not in str(p) and "\\obj\\" not in str(p)
        and "/bin/" not in str(p) and "/obj/" not in str(p)
    )

    hits: dict[str, list[tuple[str, int, str]]] = defaultdict(list)
    per_file: dict[str, int] = defaultdict(int)

    for path in files:
        rel = path.relative_to(ROOT).as_posix()
        for n, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
            if not COMMENT.match(line):
                continue
            for key, _, pattern in CATEGORIES:
                if pattern.search(line):
                    if key == "OWN" and OWN_MENTION.search(line):
                        break      # a history/meta MENTION of the marker, not a declaration
                    hits[key].append((rel, n, clean(line)))
                    per_file[rel] += 1
                    break          # one line counts once, in the first category that claims it

    lines: list[str] = []
    lines.append("# 未移植・近似・無観測の棚卸し（自動生成）")
    lines.append("")
    lines.append("> **AUTO-GENERATED by `audit/scripts/Build-ApproximationInventory.py`"
                 " — 手で編集しない。**")
    lines.append("> 元は各 `.cs` のコメントで、**直すのはコメントの側**。再生成すればここに出る。")
    lines.append("")
    lines.append("台帳は**測った所**が LilyPond と合っているかを言う。**測っていない所が"
                 "どれだけ違う形をしているか**は言えない。この表はその欠けている側の数で、")
    lines.append("「全点 exact だが機械は別物」という状態を検知するための唯一の材料。")
    lines.append("")
    lines.append("⚠️ **ここに載ること自体は欠陥ではない。** ほとんどは意図的で、論証も付いている。"
                 "答えるのは「いくつあって、どこに固まっているか」だけ。")
    lines.append("")
    lines.append("## 総数")
    lines.append("")
    lines.append("| 区分 | 件数 | 意味 |")
    lines.append("|---|---:|---|")
    for key, desc, _ in CATEGORIES:
        lines.append(f"| `{key}` | {len(hits[key])} | {desc} |")
    lines.append(f"| **計** | **{sum(len(v) for v in hits.values())}** | |")
    lines.append("")
    lines.append("## 密度の高いファイル（上位 12）")
    lines.append("")
    lines.append("| ファイル | 件数 |")
    lines.append("|---|---:|")
    for rel, n in sorted(per_file.items(), key=lambda kv: -kv[1])[:12]:
        lines.append(f"| `{rel}` | {n} |")
    lines.append("")

    for key, desc, _ in CATEGORIES:
        lines.append(f"## {key} — {desc}（{len(hits[key])} 件）")
        lines.append("")
        current = ""
        for rel, n, text in hits[key]:
            if rel != current:
                lines.append(f"### `{rel}`")
                current = rel
            lines.append(f"- **:{n}** {text}")
        lines.append("")

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="")
    for key, _, _ in CATEGORIES:
        print(f"{key:10} {len(hits[key])}")
    print(f"{'TOTAL':10} {sum(len(v) for v in hits.values())}")
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
