// Lily# - Music notation compiler
// AUTO-GENERATED by audit/scripts/Extract-EmmentalerGlyphs.py — DO NOT EDIT MANUALLY.
// Re-run the script after the bundled Emmentaler font is updated.
// Source font: LilySharp.Core/Fonts/emmentaler-20.otf
//
// Every constant is resolved from the glyph's feta NAME, the way LilyPond asks
// for glyphs (lily/clef.cc:29-52, lily/note-head.cc). The code points themselves
// are private-use and NOT stable across font builds — LilyPond 2.26.0 moves 73 of
// them — so the name is what carries meaning and the number is just today's slot.

namespace LilySharp.Core.Svg;

internal static partial class EmmentalerGlyphs
{
    // === Clefs ===
    /// <summary>clefs.G</summary>
    public const char GClef = '\uE089';
    /// <summary>clefs.G_change (smaller, for clef changes)</summary>
    public const char GClefChange = '\uE08A';
    /// <summary>clefs.G (same glyph as GClef; the 8 is italic text)</summary>
    public const char GClef8va = '\uE089';
    /// <summary>clefs.F</summary>
    public const char FClef = '\uE087';
    /// <summary>clefs.F_change (smaller, for clef changes)</summary>
    public const char FClefChange = '\uE088';
    /// <summary>clefs.F (same glyph as FClef)</summary>
    public const char FClef8va = '\uE087';
    /// <summary>clefs.C</summary>
    public const char CClef = '\uE083';
    /// <summary>clefs.C_change (smaller, for clef changes)</summary>
    public const char CClefChange = '\uE084';
    /// <summary>clefs.percussion</summary>
    public const char PercussionClef = '\uE08F';
    /// <summary>clefs.percussion_change</summary>
    public const char PercussionClefChange = '\uE090';
    /// <summary>clefs.tab (6-string TAB)</summary>
    public const char TabClef = '\uE093';
    /// <summary>clefs.tab_change (smaller)</summary>
    public const char TabClefChange = '\uE094';

    // === Note heads ===
    /// <summary>noteheads.s0</summary>
    public const char NoteheadWhole = '\uE0FC';
    /// <summary>noteheads.s1</summary>
    public const char NoteheadHalf = '\uE0FD';
    /// <summary>noteheads.s2</summary>
    public const char NoteheadBlack = '\uE0FE';
    /// <summary>noteheads.sM1</summary>
    public const char NoteheadDoubleWhole = '\uE0FA';
    /// <summary>noteheads.s0diamond</summary>
    public const char NoteheadDiamondWhole = '\uE0FF';
    /// <summary>noteheads.s1diamond</summary>
    public const char NoteheadDiamondHalf = '\uE100';
    /// <summary>noteheads.s2diamond</summary>
    public const char NoteheadDiamondBlack = '\uE101';
    /// <summary>noteheads.s0triangle</summary>
    public const char NoteheadTriangleWhole = '\uE102';
    /// <summary>noteheads.s1triangle</summary>
    public const char NoteheadTriangleHalf = '\uE103';
    /// <summary>noteheads.s2triangle</summary>
    public const char NoteheadTriangleBlack = '\uE104';
    /// <summary>noteheads.s0slash</summary>
    public const char NoteheadSlashWhole = '\uE105';
    /// <summary>noteheads.s1slash</summary>
    public const char NoteheadSlashHalf = '\uE106';
    /// <summary>noteheads.s2slash</summary>
    public const char NoteheadSlashBlack = '\uE107';
    /// <summary>noteheads.s0cross</summary>
    public const char NoteheadCrossWhole = '\uE108';
    /// <summary>noteheads.s1cross</summary>
    public const char NoteheadCrossHalf = '\uE109';
    /// <summary>noteheads.s2cross</summary>
    public const char NoteheadCrossBlack = '\uE10A';
    /// <summary>noteheads.s2xcircle</summary>
    public const char NoteheadXCircle = '\uE10B';

    // === Rests ===
    /// <summary>rests.M3</summary>
    public const char RestMaxima = '\uE004';
    /// <summary>rests.M2</summary>
    public const char RestLonga = '\uE005';
    /// <summary>rests.M1</summary>
    public const char RestDoubleWhole = '\uE006';
    /// <summary>rests.0</summary>
    public const char RestWhole = '\uE000';
    /// <summary>rests.1</summary>
    public const char RestHalf = '\uE001';
    /// <summary>rests.2</summary>
    public const char RestQuarter = '\uE008';
    /// <summary>rests.3</summary>
    public const char Rest8th = '\uE00B';
    /// <summary>rests.4</summary>
    public const char Rest16th = '\uE00C';
    /// <summary>rests.5</summary>
    public const char Rest32nd = '\uE00D';
    /// <summary>rests.6</summary>
    public const char Rest64th = '\uE00E';
    /// <summary>rests.7</summary>
    public const char Rest128th = '\uE00F';

    // === Accidentals ===
    /// <summary>accidentals.flat</summary>
    public const char AccidentalFlat = '\uE021';
    /// <summary>accidentals.natural</summary>
    public const char AccidentalNatural = '\uE01D';
    /// <summary>accidentals.sharp</summary>
    public const char AccidentalSharp = '\uE013';
    /// <summary>accidentals.doublesharp</summary>
    public const char AccidentalDoubleSharp = '\uE01C';
    /// <summary>accidentals.flatflat</summary>
    public const char AccidentalDoubleFlat = '\uE02A';
    /// <summary>accidentals.sharp.slashslash.stem (quarter sharp)</summary>
    public const char AccidentalQuarterSharp = '\uE017';
    /// <summary>accidentals.sharp.slashslashslash.stemstem (three-quarter sharp)</summary>
    public const char AccidentalThreeQuarterSharp = '\uE018';
    /// <summary>accidentals.flat.slash (quarter flat)</summary>
    public const char AccidentalQuarterFlat = '\uE025';
    /// <summary>accidentals.flatflat.slash (three-quarter flat)</summary>
    public const char AccidentalThreeQuarterFlat = '\uE02B';

    // === Accidental parentheses (for courtesy/cautionary accidentals) ===
    /// <summary>accidentals.leftparen (ink left of origin, advance 0)</summary>
    public const char AccidentalLeftParen = '\uE02F';
    /// <summary>accidentals.rightparen</summary>
    public const char AccidentalRightParen = '\uE02E';

    // === Flags ===
    /// <summary>flags.u3</summary>
    public const char Flag8thUp = '\uE0D6';
    /// <summary>flags.d3</summary>
    public const char Flag8thDown = '\uE0DE';
    /// <summary>flags.u4</summary>
    public const char Flag16thUp = '\uE0D7';
    /// <summary>flags.d4</summary>
    public const char Flag16thDown = '\uE0DF';
    /// <summary>flags.u5</summary>
    public const char Flag32ndUp = '\uE0D8';
    /// <summary>flags.d5</summary>
    public const char Flag32ndDown = '\uE0E0';
    /// <summary>flags.u6</summary>
    public const char Flag64thUp = '\uE0D9';
    /// <summary>flags.d6</summary>
    public const char Flag64thDown = '\uE0E1';
    /// <summary>flags.u7</summary>
    public const char Flag128thUp = '\uE0DA';
    /// <summary>flags.d7</summary>
    public const char Flag128thDown = '\uE0E2';

    // === Augmentation dot ===
    /// <summary>dots.dot</summary>
    public const char AugmentationDot = '\uE038';

    // === Time signatures (fattened digits) ===
    /// <summary>fattened.zero</summary>
    public const char TimeSig0 = '\uE0B8';
    /// <summary>fattened.one</summary>
    public const char TimeSig1 = '\uE0B9';
    /// <summary>fattened.two</summary>
    public const char TimeSig2 = '\uE0BA';
    /// <summary>fattened.three</summary>
    public const char TimeSig3 = '\uE0BB';
    /// <summary>fattened.four</summary>
    public const char TimeSig4 = '\uE0BC';
    /// <summary>fattened.five</summary>
    public const char TimeSig5 = '\uE0BE';
    /// <summary>fattened.six</summary>
    public const char TimeSig6 = '\uE0BF';
    /// <summary>fattened.seven</summary>
    public const char TimeSig7 = '\uE0C0';
    /// <summary>fattened.eight</summary>
    public const char TimeSig8 = '\uE0C2';
    /// <summary>fattened.nine</summary>
    public const char TimeSig9 = '\uE0C3';
    /// <summary>timesig.C44</summary>
    public const char TimeSigCommon = '\uE095';
    /// <summary>timesig.C22</summary>
    public const char TimeSigCutCommon = '\uE096';

    // === Articulations ===
    /// <summary>scripts.ufermata</summary>
    public const char FermataAbove = '\uE039';
    /// <summary>scripts.dfermata</summary>
    public const char FermataBelow = '\uE03A';
    /// <summary>scripts.ushortfermata (angled)</summary>
    public const char FermataShortAbove = '\uE03F';
    /// <summary>scripts.dshortfermata</summary>
    public const char FermataShortBelow = '\uE040';
    /// <summary>scripts.ulongfermata (square)</summary>
    public const char FermataLongAbove = '\uE043';
    /// <summary>scripts.dlongfermata</summary>
    public const char FermataLongBelow = '\uE044';
    /// <summary>scripts.sforzato</summary>
    public const char ArticAccentAbove = '\uE048';
    /// <summary>scripts.staccato</summary>
    public const char ArticStaccatoAbove = '\uE04A';
    /// <summary>scripts.tenuto</summary>
    public const char ArticTenutoAbove = '\uE04D';
    /// <summary>scripts.uportato</summary>
    public const char ArticPortatoAbove = '\uE04E';
    /// <summary>scripts.dportato</summary>
    public const char ArticPortatoBelow = '\uE04F';
    /// <summary>scripts.ustaccatissimo</summary>
    public const char ArticStaccatissimoAbove = '\uE04B';
    /// <summary>scripts.dstaccatissimo</summary>
    public const char ArticStaccatissimoBelow = '\uE04C';
    /// <summary>scripts.uupbow (V)</summary>
    public const char ArticUpBowAbove = '\uE056';
    /// <summary>scripts.dupbow (V, below the staff)</summary>
    public const char ArticUpBowBelow = '\uE057';
    /// <summary>scripts.udownbow (frog)</summary>
    public const char ArticDownBowAbove = '\uE058';
    /// <summary>scripts.ddownbow (frog, below the staff)</summary>
    public const char ArticDownBowBelow = '\uE059';
    /// <summary>scripts.flageolet (harmonic circle)</summary>
    public const char ArticFlageolet = '\uE064';
    /// <summary>scripts.umarcato</summary>
    public const char ArticMarcatoAbove = '\uE050';
    /// <summary>scripts.dmarcato</summary>
    public const char ArticMarcatoBelow = '\uE051';
    /// <summary>scripts.stopped (+)</summary>
    public const char ArticStopped = '\uE055';
    /// <summary>scripts.upedalheel (U)</summary>
    public const char PedalHeelUp = '\uE05F';
    /// <summary>scripts.dpedalheel</summary>
    public const char PedalHeelDown = '\uE060';
    /// <summary>scripts.upedaltoe (V)</summary>
    public const char PedalToeUp = '\uE061';
    /// <summary>scripts.dpedaltoe</summary>
    public const char PedalToeDown = '\uE062';
    /// <summary>scripts.thumb (cello thumb position)</summary>
    public const char ArticThumb = '\uE047';

    // === Ornaments ===
    /// <summary>scripts.reverseturn</summary>
    public const char OrnReverseTurn = '\uE05A';
    /// <summary>scripts.turn</summary>
    public const char OrnTurn = '\uE05B';
    /// <summary>scripts.trill</summary>
    public const char OrnTrill = '\uE05E';
    /// <summary>scripts.trill_element (the trill line's repeating unit)</summary>
    public const char OrnTrillElement = '\uE070';
    /// <summary>scripts.segno</summary>
    public const char MarkSegno = '\uE065';
    /// <summary>scripts.coda</summary>
    public const char MarkCoda = '\uE067';
    /// <summary>scripts.prall</summary>
    public const char OrnPrall = '\uE073';
    /// <summary>scripts.mordent</summary>
    public const char OrnMordent = '\uE074';
    /// <summary>scripts.prallprall</summary>
    public const char OrnPrallPrall = '\uE075';

    // === Breathing signs ===
    /// <summary>scripts.rcomma (\breathe)</summary>
    public const char BreathComma = '\uE069';
    /// <summary>scripts.caesura.straight (\caesura)</summary>
    public const char CaesuraStraight = '\uE080';

    // === Metronome (regular noteheads) ===
    /// <summary>noteheads.sM1</summary>
    public const char MetNoteDoubleWhole = '\uE0FA';
    /// <summary>noteheads.s0</summary>
    public const char MetNoteWhole = '\uE0FC';
    /// <summary>noteheads.s1</summary>
    public const char MetNoteHalfUp = '\uE0FD';
    /// <summary>noteheads.s2</summary>
    public const char MetNoteQuarterUp = '\uE0FE';
    /// <summary>noteheads.s2</summary>
    public const char MetNote8thUp = '\uE0FE';
    /// <summary>noteheads.s2</summary>
    public const char MetNote16thUp = '\uE0FE';

    // === Repeat dots ===
    /// <summary>dots.dot</summary>
    public const char RepeatDots = '\uE038';
}
